In [2]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
path = str(Path.cwd().parent)
print(path)
sys.path.insert(1, path)

c:\Users\jaesc2\GitHub\skforecast


In [3]:
# Libraries
# ==============================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from copy import deepcopy
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from lightgbm import LGBMRegressor

from skforecast.exceptions import OneStepAheadValidationWarning
from skforecast.datasets import fetch_dataset
from skforecast.preprocessing import RollingFeatures
from skforecast.recursive import ForecasterRecursive
from skforecast.direct import ForecasterDirect
from skforecast.recursive import ForecasterRecursiveMultiSeries
from skforecast.direct import ForecasterDirectMultiVariate

In [4]:
y = pd.Series(np.arange(20), name='y')

In [10]:
forecaster = ForecasterRecursive(
                 regressor = LinearRegression(),
                 lags      = 5,
                 differentiation = 1
             )

forecaster.fit(y=y)

In [13]:
forecaster.window_size

6

In [14]:
forecaster.differentiation

1

In [11]:
forecaster.window_size - forecaster.differentiation

5

In [12]:
y

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
Name: y, dtype: int32

In [8]:
y[forecaster.window_size - forecaster.differentiation]

5

In [15]:
# Create training matrices
# ==============================================================================
X_train, y_train = forecaster.create_train_X_y(y=y)
X_train.head(3)

lag_1  lag_2  lag_3  lag_4  lag_5
6    1.0    1.0    1.0    1.0    1.0
7    1.0    1.0    1.0    1.0    1.0
8    1.0    1.0    1.0    1.0    1.0

In [ ]:
X = forecaster.regressor.predict(X_train)
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
X_undiff = np.insert(X, 0, 1)
X_undiff = np.cumsum(X_undiff, dtype=float)
X_undiff

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
X_undiff = np.insert(X_undiff, 0, 5)
X_undiff = np.cumsum(X_undiff, dtype=float)
X_undiff

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19.])