In [1]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
path = str(Path.cwd().parent)
print(path)
sys.path.insert(1, path)

c:\Users\jaesc2\GitHub\skforecast


In [75]:
import pytest
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from skforecast.preprocessing import RollingFeatures
from skforecast.recursive import ForecasterRecursive
from skforecast.direct import ForecasterDirect

# Fixtures
from skforecast.direct.tests.tests_forecaster_direct.fixtures_forecaster_direct import y
from skforecast.direct.tests.tests_forecaster_direct.fixtures_forecaster_direct import exog, exog_predict

In [88]:
forecaster = ForecasterDirect(
                    regressor = LinearRegression(),
                    steps     = 5,
                    lags      = 5
                )
forecaster.fit(y=y)

recommended_n_boot = 5
forecaster.in_sample_residuals_by_bin_[1] = forecaster.in_sample_residuals_by_bin_[1][:recommended_n_boot]
for k, v in forecaster.in_sample_residuals_by_bin_.items():
    if k != 1:
        forecaster.in_sample_residuals_by_bin_[k] = v[:recommended_n_boot - 1]
    
results = forecaster.predict_bootstrapping(
    steps=5, n_boot=recommended_n_boot, use_in_sample_residuals=True, use_binned_residuals=True
)
results

8.0
[-0.46599771 -0.13167749 -0.2400648   0.38610882 -0.46599771]
4.0
[-0.06597795 -0.06247223 -0.30764313  0.11784057 -0.30764313]
2.0
[-0.0450625  -0.04970559 -0.27109241 -0.2054548  -0.27109241]
1.0
[ 0.01079722  0.31667074  0.02045466 -0.03134715 -0.18923835]
1.0
[ 0.01079722  0.31667074  0.02045466 -0.03134715 -0.18923835]


pred_boot_0  pred_boot_1  pred_boot_2  pred_boot_3  pred_boot_4
50     0.087196     0.421516     0.313129     0.939302     0.087196
51     0.417073     0.420579     0.175408     0.600892     0.175408
52     0.404750     0.400107     0.178720     0.244358     0.178720
53     0.424213     0.730087     0.433870     0.382069     0.224177
54     0.430659     0.736532     0.440316     0.388514     0.230623

In [87]:
recommended_n_boot = 5
in_sample_residuals_by_bin_ = forecaster.in_sample_residuals_by_bin_.copy()
in_sample_residuals_by_bin_[1] = in_sample_residuals_by_bin_[1][:recommended_n_boot]
for k, v in in_sample_residuals_by_bin_.items():
    if k != 1:
        in_sample_residuals_by_bin_[k] = v[:recommended_n_boot - 1]

in_sample_residuals_by_bin_

{0: array([ 0.35398646, -0.01070607, -0.0121861 ,  0.06634067]),
 1: array([ 0.01079722,  0.31667074,  0.02045466, -0.03134715, -0.18923835]),
 2: array([-0.0450625 , -0.04970559, -0.27109241, -0.2054548 ]),
 3: array([ 0.01474554, -0.12607334, -0.40848077,  0.1781821 ]),
 4: array([-0.06597795, -0.06247223, -0.30764313,  0.11784057]),
 5: array([ 0.47165077, -0.01760355, -0.39344615,  0.47603728]),
 6: array([ 0.21672936,  0.00902857, -0.11833943,  0.20465353]),
 7: array([-0.01111603, -0.29143333, -0.10171245, -0.05190446]),
 8: array([-0.46599771, -0.13167749, -0.2400648 ,  0.38610882]),
 9: array([ 0.06586613,  0.27294283,  0.13207642, -0.05288698])}

In [85]:
results.to_numpy()

array([[0.0871959 , 0.42151611, 0.31312881, 0.93930242, 0.0871959 ],
       [0.41707327, 0.42057899, 0.17540809, 0.60089178, 0.17540809],
       [0.40475029, 0.4001072 , 0.17872038, 0.24435799, 0.17872038],
       [0.42421302, 0.73008654, 0.43387046, 0.38206866, 0.22417746],
       [0.43065853, 0.73653206, 0.44031597, 0.38851417, 0.23062297]])

In [11]:
forecaster.binner_intervals_

{0.0: (77.11104390221573, 95.19313158258132),
 1.0: (95.19313158258132, 107.10836783689707),
 2.0: (107.10836783689707, 122.98049619443195)}

In [47]:
import re
import pytest
import numpy as np
import pandas as pd
from sklearn.exceptions import NotFittedError
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMRegressor

from skforecast.preprocessing import RollingFeatures
from skforecast.preprocessing import TimeSeriesDifferentiator
from skforecast.recursive import ForecasterRecursive
from scipy.stats import norm
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

# Fixtures
from skforecast.recursive.tests.tests_forecaster_recursive.fixtures_forecaster_recursive import y
from skforecast.recursive.tests.tests_forecaster_recursive.fixtures_forecaster_recursive import exog
from skforecast.recursive.tests.tests_forecaster_recursive.fixtures_forecaster_recursive import exog_predict
from skforecast.recursive.tests.tests_forecaster_recursive.fixtures_forecaster_recursive import data  # to test results when using differentiation


In [63]:
forecaster = ForecasterDirect(LinearRegression(), steps=5, lags=3)
forecaster.fit(y=y)
results = forecaster._predict_interval_conformal(
    steps=5, nominal_coverage=0.95, use_in_sample_residuals=True, use_binned_residuals=True
)
results

pred  lower_bound  upper_bound
50  0.518835     0.088134     0.949536
51  0.458472     0.043262     0.873681
52  0.399627    -0.047581     0.846835
53  0.404529    -0.042679     0.851737
54  0.415346    -0.031862     0.862554

In [64]:
results.to_numpy()

array([[ 0.51883519,  0.08813429,  0.94953609],
       [ 0.4584716 ,  0.04326184,  0.87368136],
       [ 0.39962743, -0.04758052,  0.84683537],
       [ 0.40452904, -0.0426789 ,  0.85173698],
       [ 0.41534557, -0.03186238,  0.86255351]])