In [1]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
path = str(Path.cwd().parent)
print(path)
sys.path.insert(1, path)

import numpy as np
import pandas as pd

c:\Users\jaesc2\GitHub\skforecast


In [93]:
import keras
import numpy as np
import pandas as pd

from skforecast.deep_learning import ForecasterRnn
from skforecast.deep_learning.utils import create_and_compile_model

series = pd.DataFrame(
    {
        "1": pd.Series(np.arange(50.))
    }
)
lags = 3
steps = 4
levels = ["1"]
activation = "relu"
optimizer = keras.optimizers.Adam(learning_rate=0.01)
loss = keras.losses.MeanSquaredError()
recurrent_units = 100
dense_units = [128, 64]


model = create_and_compile_model(
    series=series,
    lags=lags,
    steps=steps,
    levels=levels,
    recurrent_units=recurrent_units,
    dense_units=dense_units,
    activation=activation,
    optimizer=optimizer,
    loss=loss,
)

keras version: 3.6.0
Using backend: tensorflow
tensorflow version: 2.18.0


In [94]:
forecaster = ForecasterRnn(model, levels, lags=lags)
forecaster.fit(series)

c:\Users\jaesc2\Miniconda3\envs\skforecast_py11_2\Lib\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adam', because it has 20 variables whereas the saved optimizer has 2 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3242  


In [95]:
forecaster.series_names_in_

['1']

In [96]:
forecaster.levels

['1']

In [97]:
forecaster.last_window_

1
47  47.0
48  48.0
49  49.0

In [98]:
predictions = forecaster._create_predict_inputs(steps=3, levels=['1', '2', '3'])
predictions

ValueError: `levels` names must be included in the series used during fit (['1']). Got ['1', '2', '3'].

In [99]:
predictions = forecaster.predict(steps=3, levels=['1'])
predictions

[[24.5544  ]
 [25.075363]
 [24.090693]]
3 1
['1' '1' '1']
[24.5544   25.075363 24.090693]
Index([50, 51, 52], dtype='int64')


level       pred
50     1  24.554399
51     1  25.075363
52     1  24.090693

In [80]:
predictions = forecaster.predict(steps=3, levels=['1', '2'])
predictions

[[10.150858   19.854595    0.22463234]
 [14.979551    8.125578   -0.13503803]
 [28.455023   14.110964    0.1882439 ]]
3 3
['1' '2' '3' '1' '2' '3' '1' '2' '3']
[10.150858   19.854595    0.22463234 14.979551    8.125578   -0.13503803
 28.455023   14.110964    0.1882439 ]
Index([50, 50, 50, 51, 51, 51, 52, 52, 52], dtype='int64')


level       pred
50     1  10.150858
50     2  19.854595
51     1  14.979551
51     2   8.125578
52     1  28.455023
52     2  14.110964

In [81]:
predictions[predictions['level'].isin(['1'])]

level       pred
50     1  10.150858
51     1  14.979551
52     1  28.455023

In [ ]:
predictions = predictions[predictions['level'].isin(levels)]